apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
kind: KnativeEventing
apiVersion: operator.knative.dev/v1beta1
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec: {}
