apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: openshift-lightspeed-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: OpenShift Lightspeed
  sourceType: grpc
  image: quay.io/openshift-lightspeed/lightspeed-catalog:alpha-0.0.2
  updateStrategy:
    registryPoll:
     interval: 10m