kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: openshift-lightspeed
  labels:
    kubernetes.io/metadata.name: openshift-lightspeed
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.24
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.24
    security.openshift.io/scc.podSecurityLabelSync: 'true'
  annotations:
    openshift.io/sa.scc.mcs: 's0:c27,c14'
    openshift.io/sa.scc.supplemental-groups: 1000730000/10000
    openshift.io/sa.scc.uid-range: 1000730000/10000
spec:
  finalizers:
    - kubernetes
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/lightspeed-operator.openshift-lightspeed: ''
  name: lightspeed-operator
  namespace: openshift-lightspeed
spec:
  channel: preview
  installPlanApproval: Automatic
  name: lightspeed-operator
  source: openshift-lightspeed-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: lightspeed-operator.v0.0.1