# These are for the operator testing - cluster deployment
apiVersion: v1
data:
  apitoken: XXX
kind: Secret
metadata:
  name: openai-api-keys
  namespace: openshift-lightspeed
type: Opaque
---
apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
  llm:
    providers:
      - name: myOpenai
        type: openai
        credentialsSecretRef:
          name: openai-api-keys
        url: "https://api.openai.com/v1"
        models:
          - name: gpt-3.5-turbo
            parameters:
              maxTokensForResponse: 20
  ols:
    defaultModel: gpt-3.5-turbo
    defaultProvider: myOpenai
    logLevel: DEBUG
